language: groovy
before_install:
  - "wget http://downloads.dlang.org/releases/2013/dmd_2.064.2-0_amd64.deb -Odmd.deb"
install:
  - "sudo apt-get update"
  - "sudo apt-get install gcc-multilib"
  - "sudo dpkg -i dmd.deb"
  - "rm dmd.deb"
  - "TERM=dumb ./gradlew assemble"
script:
  - "TERM=dumb ./gradlew check"
before_deploy:
  - "mkdir deploy/builds/CI/${TRAVIS_BUILD_NUMBER} -p"
  - "cd deploy/"
  - "cp ../build/libs/* deploy/builds/CI/${TRAVIS_BUILD_NUMBER}"
deploy:
  provider: s3
  access_key_id: AKIAIHIGFEL2YAAKGPRQ
  secret_access_key:
    secure: fF6OOkiwErMIraMBQ2Kc5XYz3EK+2VDA8awpbBisjNazmDHWT+7PfswxcV1IYwiCu7h0R2zWRALs0kOtD7G2XABsMoWh++sfV+mZyxcbOdWHk79ltNA9LnvutwRcZpK3dHG0GBsq4WRB4cpT8Up68ZKUZT2HT7ILshlx3bqhzcM=
  bucket: directmyfile
  skip_cleanup: true
  on:
    repo: DirectMyFile/SimpleCI
