language: groovy
jdk: oraclejdk8
install:
  - "TERM=dumb ./gradlew tasks"
script:
  - "TERM=dumb ./gradlew jar dist"
notifications:
  irc:
    channels:
      - "irc.esper.net#directcode"
    on_success: always
    on_failure: always
