language: groovy
before_deploy: "cd build/libs/"
deploy:
  provider: s3
  access_key_id: AKIAIHIGFEL2YAAKGPRQ
  secret_access_key:
    secure: fF6OOkiwErMIraMBQ2Kc5XYz3EK+2VDA8awpbBisjNazmDHWT+7PfswxcV1IYwiCu7h0R2zWRALs0kOtD7G2XABsMoWh++sfV+mZyxcbOdWHk79ltNA9LnvutwRcZpK3dHG0GBsq4WRB4cpT8Up68ZKUZT2HT7ILshlx3bqhzcM=
  bucket: directmyfile
  on:
    repo: DirectMyFile/SimpleCI
